# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec3df6c6069e0cffb09c7a3e7fd18d1733acd841ac26777e313e411cdf56c90e5957964ebeb287cddae8e87012a6954c4e8fda568a2e59335d411f5122020cfa

test:
  secret_key_base: ca86bb4e225a3c8d050ab8f5e6ac5bf50e329f236d73d85413067318a4307bb97060e11c7b4071d9309902a74b1a2959ef556172082086a4e17de080db277f13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
